{
   "notes":[
      {
         "id":"As1",
         "src":"tuneNotes/A#1.mp3"
      },
      {
         "id":"As2",
         "src":"tuneNotes/A#2.mp3"
      },
      {
         "id":"As3",
         "src":"tuneNotes/A#3.mp3"
      },
      {
         "id":"A1",
         "src":"tuneNotes/A1.mp3"
      },
      {
         "id":"A2",
         "src":"tuneNotes/A2.mp3"
      },
      {
         "id":"A3",
         "src":"tuneNotes/A3.mp3"
      },
      {
         "id":"B1",
         "src":"tuneNotes/B1.mp3"
      },
      {
         "id":"B2",
         "src":"tuneNotes/B2.mp3"
      },
      {
         "id":"B3",
         "src":"tuneNotes/B3.mp3"
      },
      {
         "id":"Cs",
         "src":"tuneNotes/C#.mp3"
      },
      {
         "id":"Cs2",
         "src":"tuneNotes/C#2.mp3"
      },
      {
         "id":"Cs3",
         "src":"tuneNotes/C#3.mp3"
      },
      {
         "id":"Cs4",
         "src":"tuneNotes/C#4.mp3"
      },
      {
         "id":"C1",
         "src":"tuneNotes/C1.mp3"
      },
      {
         "id":"C2",
         "src":"tuneNotes/C2.mp3"
      },
      {
         "id":"C3",
         "src":"tuneNotes/C3.mp3"
      },
      {
         "id":"C4",
         "src":"tuneNotes/C4.mp3"
      },
      {
         "id":"Ds1",
         "src":"tuneNotes/D#1.mp3"
      },
      {
         "id":"Ds2",
         "src":"tuneNotes/D#2.mp3"
      },
      {
         "id":"Ds3",
         "src":"tuneNotes/D#3.mp3"
      },
      {
         "id":"Ds4",
         "src":"tuneNotes/D#4.mp3"
      },
      {
         "id":"D1",
         "src":"tuneNotes/D1.mp3"
      },
      {
         "id":"D2",
         "src":"tuneNotes/D2.mp3"
      },
      {
         "id":"D4",
         "src":"tuneNotes/D4.mp3"
      },
      {
         "id":"E1",
         "src":"tuneNotes/E1.mp3"
      },
      {
         "id":"E2",
         "src":"tuneNotes/E2.mp3"
      },
      {
         "id":"E3",
         "src":"tuneNotes/E3.mp3"
      },
      {
         "id":"E4",
         "src":"tuneNotes/E4.mp3"
      },
      {
         "id":"Fs1",
         "src":"tuneNotes/F#1.mp3"
      },
      {
         "id":"Fs2",
         "src":"tuneNotes/F#2.mp3"
      },
      {
         "id":"Fs3",
         "src":"tuneNotes/F#3.mp3"
      },
      {
         "id":"F2",
         "src":"tuneNotes/F2.mp3"
      },
      {
         "id":"F3",
         "src":"tuneNotes/F3.mp3"
      },
      {
         "id":"F4",
         "src":"tuneNotes/F4.mp3"
      },
      {
         "id":"Gs1",
         "src":"tuneNotes/G#1.mp3"
      },
      {
         "id":"Gs2",
         "src":"tuneNotes/G#2.mp3"
      },
      {
         "id":"Gs3",
         "src":"tuneNotes/G#3.mp3"
      },
      {
         "id":"G1",
         "src":"tuneNotes/G1.mp3"
      },
      {
         "id":"G2",
         "src":"tuneNotes/G2.mp3"
      },
      {
         "id":"G3",
         "src":"tuneNotes/G3.mp3"
      }
   ]
}